### ISSUE TITLE
关于中文commonsense KG

### ISSUE THREAD

**Issue by LangDaoAI** [HKUST-KnowComp/DISCOS-commonsense#2]
Hi Team，

Great work!
I want to know how to build or get chinese commonsense KG for 中文场景？

Thanks!

**Comment by tqfang** [comment]
You may check out this paper [C3KG](https://arxiv.org/abs/2204.02549) from Findings of ACL 2022.

**Comment by LangDaoAI** [comment]
Sure，I have seen the paper，and looking forward to it's opening chinese data.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
